### ISSUE TITLE
Null index on fresh clone -> cook for windows on UE 4.23

### ISSUE THREAD

**Issue by Abductcows** [AstroTechies/ModdingKit#7]
## General
I am following the steps on Astroneer mod tutorial on https://astroneermodding.readthedocs.io/. 

My crash happens at the cooking step after adding the `ExampleItem` [(tutorial step)](https://astroneermodding.readthedocs.io/en/latest/guides/kitModding.html#cooking-the-mod).  However it also happens when I tried it with a fresh configuration of ModdingKit, meaning cooking just after launching ModdingKit project on UE [(exact step)](https://astroneermodding.readthedocs.io/en/latest/guides/kitSetup.html#developing-mods).

The crash seems to be related to thse items (see crash log)
- /Game/Components_Medium/Dropship.Default__Dropship_C:ItemComponent
- /Game/Components_Medium/Dropship_ShelterSpawner.Default__Dropship_ShelterSpawner_C:ItemComponent

Do you think this is related to my system configuration? Can you replicate it? I dont have the ability to test it on another machine or VM right now.

## How to replicate
- (Using UE4.23.1-9631420) Follow the steps on https://astroneermodding.readthedocs.io/en/latest/guides/kitSetup.html up to and including the https://astroneermodding.readthedocs.io/en/latest/guides/kitSetup.html#generating-project-files.
- Open ModdingKit/Astro.uproject with UE 4.23.1-9631420
- Select File -> Cook Content for WIndows

edit: updated starting step of setup to skip the non-Unreal-Engine tutorials

## Crash log
```
...
UATHelper: Cooking (Windows):   
UATHelper: Cooking (Windows):   Script Stack (0 frames):
UATHelper: Cooking (Windows):   
UATHelper: Cooking (Windows):   LogWindows: Error: begin: stack for UAT
UATHelper: Cooking (Windows):   LogWindows: Error: === Critical error: ===
UATHelper: Cooking (Windows):   LogWindows: Error:
UATHelper: Cooking (Windows):   LogWindows: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/SavePackage.cpp] [Line: 5115]
UATHelper: Cooking (Windows):   LogWindows: Error: ItemComponent /Game/Components_Medium/Dropship.Default__Dropship_C:ItemComponent was an archetype of ItemComponent /Game/Components_Medium/Dropship_ShelterSpawner.Default__Dropship_ShelterSpawner_C:ItemComponent but returned a null index mapping the object.
UATHelper: Cooking (Windows):   LogWindows: Error:
UATHelper: Cooking (Windows):   LogWindows: Error:
...
```

## Additional Info
- UE version `4.23.1-9631420+++UE4+Release-4.23`
- This is what I use to make a fresh "installation" of ModdingKit
```bash
rd /s /q ModdingKit

git clone https://github.com/AstroTechies/ModdingKit.git

"A:\UE\UE_4.23\Engine\Binaries\DotNET\UnrealBuildTool.exe" -projectfiles -project="A:\\AstroneerModding\\ModdingKit\\Astro.uproject" -game -rocket -progress
```

**Comment by Abductcows** [comment]
I skipped this error by deleting the two items that caused the problem. Since I only want to mod my own items in this won't cause a problem for me

**Comment by schmitzrj** [comment]
I was also getting the error, but I was also able to resolve it. I replaced the file in the Modding Kit that caused the cooking operation to choke with the newer one from the unpacked game files. This project probably needs to have its files updated to reflect the latest version of the game, or a guide added to help us know what to update so we could contribute to the fix and do pull requests. That's what I plan to do, except I can only do a partial fix by uploading newer files that were causing breaks, not knowing all the files that need to be updated.
